apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-test",
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.0.0/24",
        "rangeStart": "10.10.0.100",
        "rangeEnd": "10.10.0.200",
        "gateway": "10.10.0.1"
      }
    }
